/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1_2s2023_proyecto1_202203038;

import static ipc1_2s2023_proyecto1_202203038.CrearProfe.vectorDatos;
import static ipc1_2s2023_proyecto1_202203038.LoginProfesores.vectorParaCrearBotones;
import java.io.Serializable;
import java.util.Vector;
import javax.swing.JOptionPane;

import javax.swing.SwingUtilities;
public class ActualizarDatosModuloProfe extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form ActualizarDatosModuloProfe
     */
 public ActualizarDatosModuloProfe() { // Usar el argumento 'usuario' en lugar de 'usuarioIngresado'
    initComponents();
    compararYMostrarDatosOnline();
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    CodigoActualizadoProfe2.setEditable(false);
    CorreoActualizadoProfe2.setEditable(false);
}
        Vector<Vector<String>> vectorDeDatos = CrearProfe.vectorDatos;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GeneroActualizadoProfe2 = new javax.swing.JComboBox<>();
        ContrasenaActualizadoProfe2 = new javax.swing.JTextField();
        CorreoActualizadoProfe2 = new javax.swing.JTextField();
        ApellidoActualizadoProfe2 = new javax.swing.JTextField();
        NombreActualizadoProfe2 = new javax.swing.JTextField();
        ActualizarProfeBoton2 = new javax.swing.JButton();
        RegresarBoton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CodigoActualizadoProfe2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Actualizar datos Profesor");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Correo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Género");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña");

        GeneroActualizadoProfe2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "f", "m" }));

        ActualizarProfeBoton2.setText("Actualizar");
        ActualizarProfeBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProfeBoton2ActionPerformed(evt);
            }
        });

        RegresarBoton.setText("Regresar");
        RegresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBotonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre");

        CodigoActualizadoProfe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActualizadoProfe2ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("(en correo ingrese nuevamente su correo)");

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Ver Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ContrasenaActualizadoProfe2)
                            .addComponent(CorreoActualizadoProfe2)
                            .addComponent(ApellidoActualizadoProfe2)
                            .addComponent(NombreActualizadoProfe2)
                            .addComponent(ActualizarProfeBoton2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .addComponent(RegresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CodigoActualizadoProfe2)
                            .addComponent(GeneroActualizadoProfe2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoActualizadoProfe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NombreActualizadoProfe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ApellidoActualizadoProfe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CorreoActualizadoProfe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ContrasenaActualizadoProfe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(GeneroActualizadoProfe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ActualizarProfeBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ActualizarProfeBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProfeBoton2ActionPerformed
        actualizarVectorDeDatos();
        this.dispose();
    }//GEN-LAST:event_ActualizarProfeBoton2ActionPerformed
private void compararYMostrarDatos() {
    boolean coincidePosicion5 = false;

    for (Vector<String> fila : vectorParaCrearBotones) {
        if (fila.size() >= 6) {
            String correoUsuario = fila.get(5);

            for (Vector<String> datos : vectorDeDatos) {
                if (datos.size() >= 4 && datos.get(3).equals(correoUsuario)) {
                    coincidePosicion5 = true;
                    CodigoActualizadoProfe2.setText(datos.get(0)); // Posición 0: Código
                    NombreActualizadoProfe2.setText(datos.get(1)); // Posición 1: Nombre
                    ApellidoActualizadoProfe2.setText(datos.get(2)); // Posición 2: Apellido
                    CorreoActualizadoProfe2.setText(correoUsuario); // Correo del usuario en vectorParaCrearBotones
                    GeneroActualizadoProfe2.setSelectedItem(datos.get(4)); // Posición 4: Género
                    ContrasenaActualizadoProfe2.setText(datos.get(5)); // Posición 5: Contraseña
                    break;
                }
            }
            if (coincidePosicion5) {
                break;
            }
        }
    }

    if (!coincidePosicion5) {
        JOptionPane.showMessageDialog(null, "No se encontraron datos para el usuario ingresado en modo 'Online'", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
 private void compararYMostrarDatosOnline() {

    boolean coincidePosicion4 = false;

        for (Vector<String> fila : vectorParaCrearBotones) {
            if (fila.size() >= 7 && fila.get(6).equals("Online")) {
                coincidePosicion4 = true;
                break;
            }
        }

        if (coincidePosicion4) {
            compararYMostrarDatos();
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron datos para el usuario ingresado en modo 'Online'", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

  

private void actualizarVectorDeDatos() {

    for (Vector<String> fila : vectorDeDatos) {
            fila.set(1, NombreActualizadoProfe2.getText()); // Posición 1: Nombre
            fila.set(2, ApellidoActualizadoProfe2.getText()); // Posición 2: Apellido
            fila.set(4, GeneroActualizadoProfe2.getSelectedItem().toString()); // Posición 3: Género
            fila.set(5, ContrasenaActualizadoProfe2.getText()); // Posición 4: Contraseña
            // No es necesario actualizar la posición 5, ya que representa el correo (usuarioIngresado)

            JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
            break; // Salir del bucle una vez que se actualice la fila
        
    }
}
    
    private void RegresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBotonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_RegresarBotonActionPerformed

    private void CodigoActualizadoProfe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActualizadoProfe2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActualizadoProfe2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    compararYMostrarDatos();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
    String usuarioIngresado = "NombreDeUsuario"; // Aquí debes asignar el nombre de usuario

    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(ActualizarDatosModuloProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(ActualizarDatosModuloProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(ActualizarDatosModuloProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(ActualizarDatosModuloProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ActualizarDatosModuloProfe().setVisible(true); // Pasa el usuarioIngresado como argumento
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarProfeBoton2;
    private javax.swing.JTextField ApellidoActualizadoProfe2;
    private javax.swing.JTextField CodigoActualizadoProfe2;
    private javax.swing.JTextField ContrasenaActualizadoProfe2;
    private javax.swing.JTextField CorreoActualizadoProfe2;
    private javax.swing.JComboBox<String> GeneroActualizadoProfe2;
    private javax.swing.JTextField NombreActualizadoProfe2;
    private javax.swing.JButton RegresarBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
