/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1_2s2023_proyecto1_202203038;

import static ipc1_2s2023_proyecto1_202203038.CrearCursoFrame.vectorCursos;
import static ipc1_2s2023_proyecto1_202203038.CrearProfe.vectorDatos;
import java.util.Vector;
import javax.swing.JOptionPane;
import ipc1_2s2023_proyecto1_202203038.Curso;
import java.io.Serializable;

/**
 *
 * @author Player
 */
public class LoginProfesores extends javax.swing.JFrame implements Serializable{
    String contrasenaIngresada;
    String usuarioIngresado;
    Vector<Vector<String>> vectorDeDatos = CrearProfe.vectorDatos;
 
 /**
     * Creates new form LoginProfesores
     */
    public LoginProfesores() {
        initComponents();
     this.setLocationRelativeTo(null);
     this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsuarioTxtFieldProfesor = new javax.swing.JTextField();
        ContrasenaProfesorPasswordField = new javax.swing.JPasswordField();
        IniciarSesionProfeBoton = new javax.swing.JButton();
        RegresarMenuBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido Profesor");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese su Correo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese su Contraseña");

        IniciarSesionProfeBoton.setText("Iniciar Sesion");
        IniciarSesionProfeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionProfeBotonActionPerformed(evt);
            }
        });

        RegresarMenuBoton.setText("Regresar al menu anterior");
        RegresarMenuBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarMenuBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RegresarMenuBoton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ContrasenaProfesorPasswordField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(UsuarioTxtFieldProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IniciarSesionProfeBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UsuarioTxtFieldProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ContrasenaProfesorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(IniciarSesionProfeBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegresarMenuBoton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static Vector<Vector<String>> vectorParaCrearBotones = new Vector<>();
    private void IniciarSesionProfeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionProfeBotonActionPerformed
        // TODO add your handling code here:
        VerificarContrasena();
        
    }//GEN-LAST:event_IniciarSesionProfeBotonActionPerformed

    private void RegresarMenuBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarMenuBotonActionPerformed
    // TODO add your handling code here:
        MenuPrincipal ApareceMenuAdmin = new MenuPrincipal();
        ApareceMenuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarMenuBotonActionPerformed

public void VerificarContrasena() {
    // Obtener la contraseña y el usuario ingresados por el usuario
    contrasenaIngresada = new String(ContrasenaProfesorPasswordField.getPassword());
    usuarioIngresado = UsuarioTxtFieldProfesor.getText();

    // Indicar si se encontró un usuario válido
    boolean usuarioValido = false;
    String NombreProfeModulo = null;
    String ApellidoProfeModulo = null;
    String NombreCompletoProfeModulo = null;

    // Posiciones del vector: codigo = 0, nombre = 1, apellido = 2, correo = 3, genero = 4, contrasena = 5
    for (Vector<String> fila : vectorDeDatos) {
        if (fila.size() >= 5) {
            String usuarioEnVector = fila.get(3); // El usuario se encuentra en la posición 3
            String contrasenaEnVector = fila.get(5); // La contraseña se encuentra en la posición 5

            // Verificar si el usuario ingresado coincide con el usuario en el vector
            if (usuarioIngresado.equals(usuarioEnVector) && contrasenaIngresada.equals(contrasenaEnVector)) {
                usuarioValido = true;
                NombreProfeModulo = fila.get(1); // Nombre del profesor en la posición 1
                ApellidoProfeModulo = fila.get(2); // Apellido del profesor en la posición 2
                NombreCompletoProfeModulo = NombreProfeModulo + " " + ApellidoProfeModulo; // Nombre completo del profesor
                break;
            }
        }
    }

    if (usuarioValido) {
        // Inicio de sesión exitoso
        JOptionPane.showMessageDialog(null, "Inicio de sesión efectuado correctamente");

        // Buscar coincidencias en vectorCursos y agregar los datos correspondientes
        for (Vector<String> filaCurso : vectorCursos) {
            if (filaCurso.size() >= 5 && filaCurso.get(4) != null && filaCurso.get(4).equals(NombreCompletoProfeModulo)) {
                // Agregar los datos de filaCurso a vectorParaCrearBotones
                Vector<String> cursoParaBoton = new Vector<>(filaCurso);
                cursoParaBoton.add(usuarioIngresado);
                vectorParaCrearBotones.add(cursoParaBoton);
            }
        }

       
    cambiarEstadoSesionOnline();
       for (Vector<String> elemento : vectorParaCrearBotones) {
            for (String valor : elemento) {
                System.out.print(valor + " "); // Mostrar cada valor separado por un espacio
            }
            System.out.println(); // Nueva línea para separar cada elemento del vector
        }
        ModuloProfesorFrame Aparece33 = new ModuloProfesorFrame();
        Aparece33.setVisible(true);
    } else {
        // Inicio de sesión fallido
        JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

public void cambiarEstadoSesionOnline() {
    // Buscar coincidencias en vectorParaCrearBotones
    for (Vector<String> filaCurso : vectorParaCrearBotones) {
        if (filaCurso.size() >= 6 && filaCurso.get(5) != null && filaCurso.get(5).equals(usuarioIngresado)) {
            // Verificar si ya existe "Offline" en la posición 6
            int posicionEstadoSesion = 6;
            if (filaCurso.size() > posicionEstadoSesion) {
                if ("Offline".equals(filaCurso.get(posicionEstadoSesion))) {
                    filaCurso.set(posicionEstadoSesion, "Online"); // Reemplazar "Offline" por "Online" en la posición 6
                }
            } else {
                filaCurso.add("Online"); // Agregar "Online" en la posición 6 del vector
            }
        }
    }
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginProfesores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContrasenaProfesorPasswordField;
    private javax.swing.JButton IniciarSesionProfeBoton;
    private javax.swing.JButton RegresarMenuBoton;
    private javax.swing.JTextField UsuarioTxtFieldProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
