/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1_2s2023_proyecto1_202203038;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.Serializable;
import java.util.Vector;

/**
 *
 * @author Player
 */
public class MenuPrincipal extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
     this.setLocationRelativeTo(null);
     this.setResizable(false);
this.addWindowListener(new WindowAdapter(){
        @Override
        public void windowClosing(WindowEvent e){
        Appdata.serializar();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CerrarProgramaBoton = new javax.swing.JButton();
        EstudianteLoginBoton = new javax.swing.JButton();
        ProfesorLoginBoton = new javax.swing.JButton();
        AdminLoginBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 51, 255));

        CerrarProgramaBoton.setText("Cerrar Programa");
        CerrarProgramaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarProgramaBotonActionPerformed(evt);
            }
        });

        EstudianteLoginBoton.setText("Estudiante");
        EstudianteLoginBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteLoginBotonActionPerformed(evt);
            }
        });

        ProfesorLoginBoton.setText("Profesor");
        ProfesorLoginBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfesorLoginBotonActionPerformed(evt);
            }
        });

        AdminLoginBoton.setText("Administrador");
        AdminLoginBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLoginBotonMouseClicked(evt);
            }
        });
        AdminLoginBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("De click en la opcion que desea ingresar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CerrarProgramaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProfesorLoginBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminLoginBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EstudianteLoginBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(AdminLoginBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfesorLoginBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstudianteLoginBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(CerrarProgramaBoton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminLoginBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginBotonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AdminLoginBotonActionPerformed

    private void AdminLoginBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLoginBotonMouseClicked
        // TODO add your handling code here:
         LoginAdmin ApareceMenuAdmin = new LoginAdmin();
            ApareceMenuAdmin.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_AdminLoginBotonMouseClicked

    private void CerrarProgramaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarProgramaBotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_CerrarProgramaBotonActionPerformed

    private void ProfesorLoginBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfesorLoginBotonActionPerformed
        // TODO add your handling code here
               Vector<Vector<String>> vectorDeDatos = CrearProfe.vectorDatos;
                LoginProfesores Aparece = new LoginProfesores();
                      Aparece.setVisible(true);
                this.dispose();

    }//GEN-LAST:event_ProfesorLoginBotonActionPerformed

    private void EstudianteLoginBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteLoginBotonActionPerformed
        // TODO add your handling code here:
                LoginAlumnoJframe Aparece = new LoginAlumnoJframe();
                      Aparece.setVisible(true);
                      this.dispose();
    }//GEN-LAST:event_EstudianteLoginBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLoginBoton;
    private javax.swing.JButton CerrarProgramaBoton;
    private javax.swing.JButton EstudianteLoginBoton;
    private javax.swing.JButton ProfesorLoginBoton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
