/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1_2s2023_proyecto1_202203038;


import static ipc1_2s2023_proyecto1_202203038.CrearProfe.vectorDatos;
import java.util.Vector;
import javax.swing.JOptionPane;

import javax.swing.SwingUtilities;

/**
 *
 * @author Player
 */
public class ActualizarProfesor extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarProfesor
     */
    public ActualizarProfesor() {
        initComponents();
        this.setLocationRelativeTo(null);
     this.setResizable(false);

    }
 
    public static void main(String[] args) {
        // Supongamos que tienes un vector de datos llamado vectorDeDatos
        Vector<Vector<String>> vectorDeDatos = CrearProfe.vectorDatos;

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ActualizarProfeBoton = new javax.swing.JButton();
        CodigoActualizadoProfe = new javax.swing.JTextField();
        NombreActualizadoProfe = new javax.swing.JTextField();
        ApellidoActualizadoProfe = new javax.swing.JTextField();
        CorreoActualizadoProfe = new javax.swing.JTextField();
        ContrasenaActualizadoProfe = new javax.swing.JTextField();
        GeneroActualizadoProfe = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Actualizar datos profesor");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Correo");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Genero");

        ActualizarProfeBoton.setForeground(new java.awt.Color(0, 0, 0));
        ActualizarProfeBoton.setText("Actualizar");
        ActualizarProfeBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarProfeBotonMouseClicked(evt);
            }
        });
        ActualizarProfeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProfeBotonActionPerformed(evt);
            }
        });

        ApellidoActualizadoProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActualizadoProfeActionPerformed(evt);
            }
        });

        ContrasenaActualizadoProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActualizadoProfeActionPerformed(evt);
            }
        });

        GeneroActualizadoProfe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "f", "m"}));
        GeneroActualizadoProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActualizadoProfeActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar al menu anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ActualizarProfeBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CodigoActualizadoProfe)
                                .addComponent(NombreActualizadoProfe)
                                .addComponent(ApellidoActualizadoProfe)
                                .addComponent(CorreoActualizadoProfe)
                                .addComponent(ContrasenaActualizadoProfe)
                                .addComponent(GeneroActualizadoProfe, 0, 377, Short.MAX_VALUE)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CodigoActualizadoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NombreActualizadoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ApellidoActualizadoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CorreoActualizadoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ContrasenaActualizadoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(GeneroActualizadoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(ActualizarProfeBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarProfeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProfeBotonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ActualizarProfeBotonActionPerformed

    private void ActualizarProfeBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarProfeBotonMouseClicked
    // Obtener el vector de datos desde CrearProfe
       Vector<Vector<String>> vectorDeDatos = CrearProfe.vectorDatos;

       String CodigoNuevoProfe = CodigoActualizadoProfe.getText();
       String NombreProfeNuevo = NombreActualizadoProfe.getText();
       String ApellidoProfeNuevo = ApellidoActualizadoProfe.getText();
       String CorreoProfeNuevo = CorreoActualizadoProfe.getText();
       String ContraseñaProfeNuevo = ContrasenaActualizadoProfe.getText();
       String GeneroNuevoProfe = (String) GeneroActualizadoProfe.getSelectedItem();

       boolean codigoEncontrado = false;

       // Actualizar los datos en el mismo vectorDeDatos
       for (Vector<String> fila : vectorDeDatos) {
           // Verifica que la fila tenga al menos 5 elementos y que ninguno sea nulo
           if (fila.size() >= 5 &&
               fila.get(0) != null &&
               fila.get(1) != null &&
               fila.get(2) != null &&
               fila.get(3) != null &&
               fila.get(4) != null &&
               fila.get(0).equals(CodigoNuevoProfe)) {
               fila.set(1, NombreProfeNuevo);
               fila.set(2, ApellidoProfeNuevo);
               fila.set(3, CorreoProfeNuevo);
               fila.set(4, GeneroNuevoProfe); // Colocar el género en la posición 5
               fila.set(5, ContraseñaProfeNuevo); // Colocar la contraseña en la posición 4

               codigoEncontrado = true;
               break; // Si encontramos una coincidencia, salimos del bucle
           }
       }

       if (codigoEncontrado) {
           // Limpiar los campos de texto después de guardar
           CodigoActualizadoProfe.setText("");
           NombreActualizadoProfe.setText("");
           ApellidoActualizadoProfe.setText("");
           CorreoActualizadoProfe.setText("");
           ContrasenaActualizadoProfe.setText("");
           GeneroActualizadoProfe.setSelectedIndex(0);

           JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
           this.dispose();
       } else {
           JOptionPane.showMessageDialog(null, "No existe el código ingresado", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_ActualizarProfeBotonMouseClicked

    private void ApellidoActualizadoProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActualizadoProfeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActualizadoProfeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ContrasenaActualizadoProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActualizadoProfeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActualizadoProfeActionPerformed

    private void GeneroActualizadoProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActualizadoProfeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroActualizadoProfeActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarProfeBoton;
    private javax.swing.JTextField ApellidoActualizadoProfe;
    private javax.swing.JTextField CodigoActualizadoProfe;
    private javax.swing.JTextField ContrasenaActualizadoProfe;
    private javax.swing.JTextField CorreoActualizadoProfe;
    private javax.swing.JComboBox<String> GeneroActualizadoProfe;
    private javax.swing.JTextField NombreActualizadoProfe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
