/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1_2s2023_proyecto1_202203038;

import static ipc1_2s2023_proyecto1_202203038.CursoPlantillaModuloProfe.vectorAlumnosAsignadosAsignados;
import static ipc1_2s2023_proyecto1_202203038.ModuloAdmin.vectorAlumnos;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Player
 */
public class AlumnoDesasignarFrame extends javax.swing.JFrame {

    /**
     * Creates new form AlumnoDesasignarFrame
     */
    private String codigoEstudiante;
    
 public AlumnoDesasignarFrame(String codigoEstudiante) {
        initComponents();
        this.codigoEstudiante = codigoEstudiante;
        cargarDatosEstudiante(codigoEstudiante);
        setLocationRelativeTo(null);
        setResizable(false);
        
cargarImagenEnLabel(labelAlumnoFoto, "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png", 327, 190);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FotoEstudiantePanel = new javax.swing.JPanel();
        labelAlumnoFoto = new javax.swing.JLabel();
        nombreAlumnoCursotxt = new javax.swing.JTextField();
        apellidoAlumnoCursotxt = new javax.swing.JTextField();
        correoAlumnoCursotxt = new javax.swing.JTextField();
        contrasenaAlumnoCursotxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        generoAlumnoCursotxt = new javax.swing.JTextField();
        EliminarEstudiantedelCurso = new javax.swing.JButton();
        RegresarBoton = new javax.swing.JButton();
        codigoAlumnoCursotxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ver más informacion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Foto");

        javax.swing.GroupLayout FotoEstudiantePanelLayout = new javax.swing.GroupLayout(FotoEstudiantePanel);
        FotoEstudiantePanel.setLayout(FotoEstudiantePanelLayout);
        FotoEstudiantePanelLayout.setHorizontalGroup(
            FotoEstudiantePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAlumnoFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FotoEstudiantePanelLayout.setVerticalGroup(
            FotoEstudiantePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAlumnoFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Correo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Genero");

        EliminarEstudiantedelCurso.setBackground(new java.awt.Color(255, 102, 102));
        EliminarEstudiantedelCurso.setForeground(new java.awt.Color(102, 0, 0));
        EliminarEstudiantedelCurso.setText("Eliminar estudiante del curso");
        EliminarEstudiantedelCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEstudiantedelCursoActionPerformed(evt);
            }
        });

        RegresarBoton.setText("Regresar");
        RegresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBotonActionPerformed(evt);
            }
        });

        codigoAlumnoCursotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoAlumnoCursotxtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(RegresarBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EliminarEstudiantedelCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nombreAlumnoCursotxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FotoEstudiantePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidoAlumnoCursotxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correoAlumnoCursotxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasenaAlumnoCursotxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generoAlumnoCursotxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(codigoAlumnoCursotxt, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(FotoEstudiantePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoAlumnoCursotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreAlumnoCursotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoAlumnoCursotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoAlumnoCursotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenaAlumnoCursotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(generoAlumnoCursotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarEstudiantedelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBotonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_RegresarBotonActionPerformed

    private void EliminarEstudiantedelCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEstudiantedelCursoActionPerformed
        // TODO add your handling code here:
        desasignarAlumno();
        this.dispose();
    }//GEN-LAST:event_EliminarEstudiantedelCursoActionPerformed

       

 private void cargarImagenEnLabel(JLabel label, String url, int width, int height) {
    try {
        URL imageUrl = new URL(url);
        ImageIcon originalImageIcon = new ImageIcon(imageUrl);
        
        // Escalar la imagen al tamaño deseado
        Image originalImage = originalImageIcon.getImage();
        Image scaledImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
        label.setIcon(scaledImageIcon);
    } catch (IOException e) {
        e.printStackTrace();
    }
}
  
    private void desasignarAlumno() {
    // Obtener el código ingresado por el usuario desde el campo de texto
    String codigoIngresado = codigoAlumnoCursotxt.getText();

    // Iterar a través del vectorAlumnosAsignadosAsignados para buscar el código ingresado
    for (int i = 0; i < vectorAlumnosAsignadosAsignados.size(); i++) {
        Vector<String> fila = vectorAlumnosAsignadosAsignados.get(i);
        if (fila.size() > 0 && fila.get(0).equals(codigoIngresado)) {
            // Si se encuentra el código, eliminar la fila
            vectorAlumnosAsignadosAsignados.remove(i);
            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Alumno desasignado con éxito.");
            return; // Salir del bucle una vez que se encuentre el estudiante
        }
    }

    // Si no se encontró el código, mostrar un mensaje de error
    JOptionPane.showMessageDialog(this, "No se pudo desasignar al alumno en este momento.", "Error", JOptionPane.ERROR_MESSAGE);
}
    private void codigoAlumnoCursotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoAlumnoCursotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoAlumnoCursotxtActionPerformed

    private void cargarDatosEstudiante(String codigoEstudiante) {
    
        // Supongamos que vectorAlumnosAsignadosAsignados es una lista de listas
        for (Vector<String> fila : vectorAlumnosAsignadosAsignados) {
            if (fila.get(0).equals(codigoEstudiante)) {
                // Si se encuentra el código de estudiante, cargar los datos en los JTextField
                codigoAlumnoCursotxt.setText(codigoEstudiante);
                nombreAlumnoCursotxt.setText(fila.get(1)); // Suponiendo que la posición 1 contiene el nombre
                apellidoAlumnoCursotxt.setText(fila.get(2)); // Suponiendo que la posición 2 contiene el apellido
                break; // Salir del bucle una vez que se encuentre el estudiante
            }
        }
         for (Vector<String> fila : vectorAlumnos) {
        if (fila.get(0).equals(codigoEstudiante)) {
            // Si se encuentra el código de estudiante, cargar los datos en los JTextField
            codigoAlumnoCursotxt.setText(codigoEstudiante);
            
            // Asegurarse de que haya al menos 6 elementos en la fila
            if (fila.size() > 5) {
                correoAlumnoCursotxt.setText(fila.get(3)); // Suponiendo que la posición 3 contiene el correo
                generoAlumnoCursotxt.setText(fila.get(4)); // Suponiendo que la posición 4 contiene el género
                contrasenaAlumnoCursotxt.setText(fila.get(5)); // Suponiendo que la posición 5 contiene la contraseña
            } else {
                // Si no hay suficientes elementos en la fila, dejar los campos de texto vacíos
                correoAlumnoCursotxt.setText("");
                generoAlumnoCursotxt.setText("");
                contrasenaAlumnoCursotxt.setText("");
            }
            
            break; // Salir del bucle una vez que se encuentre el estudiante
        }
    }
    }
   
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(AlumnoDesasignarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Aquí no creas una instancia directamente, espera a que se seleccione un estudiante
            // Cuando se seleccione un estudiante, obtén su código y luego crea la instancia con el constructor adecuado
            // Supongamos que tienes un método que se llama alumnoSeleccionado() que se llama cuando se selecciona un estudiante
            CursoPlantillaModuloProfe cursoPlantillaModuloProfe = new CursoPlantillaModuloProfe();
            cursoPlantillaModuloProfe.setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarEstudiantedelCurso;
    private javax.swing.JPanel FotoEstudiantePanel;
    private javax.swing.JButton RegresarBoton;
    private javax.swing.JTextField apellidoAlumnoCursotxt;
    private javax.swing.JTextField codigoAlumnoCursotxt;
    private javax.swing.JTextField contrasenaAlumnoCursotxt;
    private javax.swing.JTextField correoAlumnoCursotxt;
    private javax.swing.JTextField generoAlumnoCursotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlumnoFoto;
    private javax.swing.JTextField nombreAlumnoCursotxt;
    // End of variables declaration//GEN-END:variables
}
