/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1_2s2023_proyecto1_202203038;

import static ipc1_2s2023_proyecto1_202203038.CrearCursoFrame.vectorCursos;
import static ipc1_2s2023_proyecto1_202203038.LoginProfesores.vectorParaCrearBotones;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Player
 */
public class LoginAlumnoJframe extends javax.swing.JFrame {
  String contrasenaIngresada;
  String usuarioIngresado2;
 public static Vector<Vector<String>> vectorParaCrearBotonesAlumno = new Vector<>();


    /**
     * Creates new form LoginAlumnoJframe
     */
    public LoginAlumnoJframe() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IngresarCorreoAlumnoTxtfield = new javax.swing.JTextField();
        RegresarBoton = new javax.swing.JButton();
        IniciarSesionAlumnoBoton = new javax.swing.JButton();
        IngresarContraseñaAlumnoTxtfield = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ingrese su correo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bienvenido Alumno");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ingrese su contraseña");

        RegresarBoton.setText("Regresar");
        RegresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBotonActionPerformed(evt);
            }
        });

        IniciarSesionAlumnoBoton.setText("iniciar sesion");
        IniciarSesionAlumnoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionAlumnoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IniciarSesionAlumnoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(46, 46, 46)
                            .addComponent(IngresarCorreoAlumnoTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(IngresarContraseñaAlumnoTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(RegresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(jLabel2)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IngresarCorreoAlumnoTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IngresarContraseñaAlumnoTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(IniciarSesionAlumnoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(jLabel2)
                    .addContainerGap(291, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionAlumnoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionAlumnoBotonActionPerformed
        // TODO add your handling code here:
    VerificarContrasena();

    }//GEN-LAST:event_IniciarSesionAlumnoBotonActionPerformed

    private void RegresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBotonActionPerformed
        // TODO add your handling code here:
        MenuPrincipal ApareceMenuAdmin = new MenuPrincipal();
        ApareceMenuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarBotonActionPerformed
public void VerificarContrasena() {
    // Obtener la contraseña y el usuario ingresados por el usuario
    Vector<Vector<String>> vectorAlumnos = ModuloAdmin.vectorAlumnos;

    contrasenaIngresada = new String(IngresarContraseñaAlumnoTxtfield.getPassword());
    usuarioIngresado2 = IngresarCorreoAlumnoTxtfield.getText();

    // Indicar si se encontró un usuario válido
    boolean usuarioValido = false;
    String NombreAlumno = null;
    String ApellidoAlumno = null;
    String NombreCompletoAlumno = null;
    String codigoAlumnoAsignar = null;

    // Posiciones del vector: codigo = 0, nombre = 1, apellido = 2, correo = 3, genero = 4, contrasena = 5
    for (Vector<String> fila : vectorAlumnos) {
        if (fila.size() >= 6) {
            String usuarioEnVector2 = fila.get(3); // El usuario se encuentra en la posición 3
            String contrasenaEnVector2 = fila.get(5); // La contraseña se encuentra en la posición 5

            // Verificar si el usuario ingresado coincide con el usuario en el vector
            if (usuarioIngresado2.equals(usuarioEnVector2) && contrasenaIngresada.equals(contrasenaEnVector2)) {
                usuarioValido = true;
                NombreAlumno = fila.get(1); // Nombre del alumno en la posición 1
                ApellidoAlumno = fila.get(2); // Apellido del alumno en la posición 2
                NombreCompletoAlumno = NombreAlumno + " " + ApellidoAlumno; // Nombre completo del alumno
                codigoAlumnoAsignar = fila.get(0); // Código del alumno en la posición 0
                break;
            }
        }
    }

 if (usuarioValido) {
    // Inicio de sesión exitoso
    JOptionPane.showMessageDialog(null, "Inicio de sesión efectuado correctamente");

    // Continuar con el resto del código para buscar coincidencias en vectorAlumnos y cambiar el estado de sesión
    for (Vector<String> filaAlumno : vectorAlumnos) {
        if (filaAlumno.size() >= 4 && filaAlumno.get(3) != null && filaAlumno.get(3).equals(usuarioIngresado2)) {
            // Obtiene el código del alumno en la posición 0 del vector vectorAlumnos
            String codigoAlumno = filaAlumno.get(0);

            // Agrega usuarioIngresado a la posición 0 del vectorParaCrearBotonesAlumno
            // Agrega códigoAlumno a la posición 1 del vectorParaCrearBotonesAlumno
            Vector<String> alumnoParaBoton = new Vector<>();
            alumnoParaBoton.add(usuarioIngresado2);
            alumnoParaBoton.add(codigoAlumno);

            vectorParaCrearBotonesAlumno.add(alumnoParaBoton);
        }
    }

    // Llama a cambiarEstadoSesionOnline2() después de llenar vectorParaCrearBotonesAlumno
    cambiarEstadoSesionOnline2();

    ModuloAlumnoJFrame Aparece33 = new ModuloAlumnoJFrame();
    Aparece33.setVisible(true);
} else {
    // Inicio de sesión fallido
    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
}
}
public void cambiarEstadoSesionOnline2() {
    // Buscar coincidencias en vectorParaCrearBotonesAlumno
    for (Vector<String> filaCurso : vectorParaCrearBotonesAlumno) {
        if (filaCurso.size() >= 2 && filaCurso.get(0) != null && filaCurso.get(0).equals(usuarioIngresado2)) {
            String estadoSesion = filaCurso.size() >= 4 ? filaCurso.get(3) : null; // Obtener el estado de sesión en la posición 3 si existe
            if (estadoSesion == null || estadoSesion.equals("Offline")) {
                if (filaCurso.size() >= 4) {
                    filaCurso.set(3, "Online"); // Cambiar "Offline" o nulo por "Online" en la posición 3 si existe
                } else {
                    filaCurso.add("Online"); // Agregar "Online" si no existe la posición 3
                }
            }
        }
    }

    // Imprimir el vector para verificar
    for (Vector<String> elemento : vectorParaCrearBotonesAlumno) {
        for (String valor : elemento) {
            System.out.print(valor + " "); // Mostrar cada valor separado por un espacio
        }
        System.out.println(); // Nueva línea para separar cada elemento del vector
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAlumnoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAlumnoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAlumnoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAlumnoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAlumnoJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField IngresarContraseñaAlumnoTxtfield;
    private javax.swing.JTextField IngresarCorreoAlumnoTxtfield;
    private javax.swing.JButton IniciarSesionAlumnoBoton;
    private javax.swing.JButton RegresarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
