/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1_2s2023_proyecto1_202203038;

import static ipc1_2s2023_proyecto1_202203038.LoginAlumnoJframe.vectorParaCrearBotonesAlumno;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Player
 */
public class ModuloAlumnoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ModuloAlumnoJFrame
     */
    public ModuloAlumnoJFrame() {
        initComponents();
           this.crearBotonesSegunRepeticion(vectorParaCrearBotonesAlumno);
           this.setLocationRelativeTo(null);
           this.setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ActualizarDatosAlumnoBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ActualizarDatosBoton = new javax.swing.JButton();
        RegresarMenuBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        ActualizarDatosAlumnoBoton.setText("Actualizar Datos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cursos Asignados");

        ActualizarDatosBoton.setText("Actualizar Botones");

        RegresarMenuBoton.setText("Regresar al menu principal");
        RegresarMenuBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarMenuBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ActualizarDatosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RegresarMenuBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                        .addComponent(ActualizarDatosAlumnoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActualizarDatosAlumnoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActualizarDatosBoton)
                    .addComponent(RegresarMenuBoton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarMenuBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarMenuBotonActionPerformed
   // Iterar sobre vectorParaCrearBotonesAlumno
    for (Vector<String> filaCurso : vectorParaCrearBotonesAlumno) {
        // Verificar que filaCurso tenga al menos 3 elementos y que la posición 2 sea "Online"
        if (filaCurso.size() >= 3 && "Online".equals(filaCurso.get(2))) {
            filaCurso.set(2, "Offline");
        }
    }

    // Imprimir el vector para verificar (opcional)
    for (Vector<String> elemento : vectorParaCrearBotonesAlumno) {
        for (String valor : elemento) {
            System.out.print(valor + " "); // Mostrar cada valor separado por un espacio
        }
        System.out.println(); // Nueva línea para separar cada elemento del vector
    }

    this.dispose();
    }//GEN-LAST:event_RegresarMenuBotonActionPerformed

   public void crearBotonesSegunRepeticion(Vector<Vector<String>> vectorParaCrearBotonesAlumno) {
    int coordeandaX = 30;
    int coordeandaY = 60;

    // Iterar sobre vectorParaCrearBotones para crear los botones
    for (int i = 0; i < vectorParaCrearBotonesAlumno.size(); i++) {
        Vector<String> datosCursoAlumno = vectorParaCrearBotonesAlumno.get(i);

        // Verificar si la posición 6 contiene "Online" y la posición 7 no contiene "Offline"
        if (datosCursoAlumno.size() >= 7 && "Online".equals(datosCursoAlumno.get(6)) && !"Offline".equals(datosCursoAlumno.get(6))) {
            String nombreCursoAlumno = datosCursoAlumno.get(1); // Nombre del curso en la primera posición del vector

            // Contar cuántas veces se repite ese valor (nombreCursoAlumno)
            int cantidadRepeticiones = contarRepeticiones(vectorParaCrearBotonesAlumno, nombreCursoAlumno);

            // Crear un botón para cada repetición
            for (int j = 0; j < cantidadRepeticiones; j++) {
                JButton botonCurso = new JButton(nombreCursoAlumno);
                JLabel label = new JLabel("50: estudiantes");
                botonCurso.setBounds(coordeandaX, coordeandaY, 90, 30);

                // Agregar una acción al presionar el botón
                botonCurso.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    // Obtener el nombre del curso del botón
                    String nombreCursoAlumno = ((JButton) e.getSource()).getText();

                    // Crear una instancia de la plantilla del curso
                    CursoPlantillaModuloProfe ApareceP = new CursoPlantillaModuloProfe();

                    // Llenar la plantilla con los datos correspondientes
                    llenarPlantillaCurso(ApareceP, nombreCursoAlumno, (nombreCursoAlumno));

                    // Mostrar la plantilla del curso
                    ApareceP.setVisible(true);
                }
            });

                label.setBounds(coordeandaX, coordeandaY + 30, 100, 30);

                // Agregar el botón y la etiqueta al panel o contenedor donde desees mostrarlos.
                this.add(botonCurso);
                this.add(label);

                // Ajusta las coordenadas X e Y para la próxima iteración
                coordeandaX += 100;

                // Comprueba si coordeandaX supera 550 y ajusta las coordenadas
                if (coordeandaX >= 550) {
                    coordeandaX = 0;
                    coordeandaX += 30;                            
               
                }
            }
        }
    }
}
private void llenarPlantillaCurso(CursoPlantillaModuloProfe plantilla, String nombreCursoAlumno, String descripcionCurso) {
    plantilla.llenarPlantilla(nombreCursoAlumno, descripcionCurso);
}
public void contarYAgregar(Vector<Vector<String>> vectorParaCrearBotonesAlumno) {
    int contador = 1; // Inicializar el contador en 1

    // Iterar sobre vectorParaCrearBotonesAlumno
    for (Vector<String> datosCursoAlumno : vectorParaCrearBotonesAlumno) {
        // Verificar si la posición 1 del vector contiene datos y si la posición 7 está vacía
        if (!datosCursoAlumno.isEmpty() && datosCursoAlumno.size() > 1 && (datosCursoAlumno.size() <= 7 || datosCursoAlumno.get(7) == null || datosCursoAlumno.get(7).isEmpty())) {
            // Incrementar el contador y agregar el valor en la posición 7 del vector
            datosCursoAlumno.add(Integer.toString(contador));
            contador++;
        }
    }
}
// Método para contar las repeticiones de un valor en un vector de vectores
private int contarRepeticiones(Vector<Vector<String>> vectorParaCrearBotonesAlumno, String valorBuscado) {
    int contador = 0;

    for (Vector<String> datosCursoAlumno : vectorParaCrearBotonesAlumno) {
        String nombreCursoAlumno = datosCursoAlumno.get(1);
        if (nombreCursoAlumno.equals(valorBuscado)) {
            contador++;
        }
    }

    return contador;
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloAlumnoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloAlumnoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloAlumnoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloAlumnoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloAlumnoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarDatosAlumnoBoton;
    private javax.swing.JButton ActualizarDatosBoton;
    private javax.swing.JButton RegresarMenuBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
